import { useState, useEffect } from 'react';

// page is pre-rendered by nextjs, but data is not prapared / pre-generated by nextjs
// data fetched on the client side

function LastSalesPage() {
  const [sales, setSales] = useState();
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    setIsLoading(true);
    fetch('https://nextjs-5417c-default-rtdb.europe-west1.firebasedatabase.app/sales.json')
      .then((response) => response.json())
      .then((data) => {
        const transformedSales = [];

        for (const key in data)
          transformedSales.push({
            id: key,
            username: data[key].username,
            volume: data[key].volume,
          });

        setSales(transformedSales);
        setIsLoading(false);
      });
  }, []);

  if (isLoading) return <p> ... loading </p>;
  if (!sales) return <p> no data ... yet ? </p>;

  return (
    <ul>
      {sales.map((sale) => (
        <li key={sale.id}>
          {sale.username} - {sale.volume}
        </li>
      ))}
    </ul>
  );
}

export default LastSalesPage;
